### ISSUE TITLE
GBM crashing consistently on Mac OS X (10.9.4)

### ISSUE THREAD

**Issue by kgoldfeld** [harrysouthworth/gbm#27]
Every call to gbm (from package version 2.1, R version 3.1.1) on my Mac causes R to abort.  Is this a known issue?

![screen shot 2014-09-08 at 10 14 17 pm](https://cloud.githubusercontent.com/assets/5994273/4195784/527248c2-37c7-11e4-8eb7-f85371c321df.png)

**Comment by harrysouthworth** [comment]
This issue was moved to gbm-developers/gbm#8
