### ISSUE TITLE
Bernoulli requires the response to be in {0,1}...

### ISSUE THREAD

**Issue by Mullefa** [harrysouthworth/gbm#29]
... and similarly for other distributions. Whilst this doesn't affect the functionality of the package, it is a bit inconvenient. 

Could the requirement be lowered to factors with two levels, and implicit conversion done within `gbm.fit()` (or whatever function from within the package is being used)? 

Likewise, in the corresponding`predict()` method, could a factor be returned instead of `0`'s and `1`'s?

**Comment by baek86** [comment]
+++

**Comment by harrysouthworth** [comment]
This issue was moved to gbm-developers/gbm#6
