### ISSUE TITLE
n.minobsinnode updated?

### ISSUE THREAD

**Issue by achekroud** [harrysouthworth/gbm#48]
Hi team,

I am just revisiting some old code that used the caret package as a wrapper to gbm. I noticed it was breaking, and it seems that we now need to specify "n.minobsinnode" (specifically, the tuning grid previously required just interaction.depth, n.trees, and shrinkage). Has there been an update to gbm that I missed? Or is this, perhaps, a change in caret?

Thanks for any help you can provide,

Adam

**Comment by shanebutler** [comment]
Hi Adam, caret 6.0-47 had the change "n.minobsinnode was added as a tuning parameter to gbm models".  Have you identified any issue with gbm package directly?
Caret changelog: https://cran.rstudio.com/web/packages/caret/news.html

**Comment by achekroud** [comment]
@shanebutler that looks like the problem! Thanks for flagging the changelog, I had been looking for it in their github but couldn't find it, and didn't realise CRAN carried news about each package. Thanks again for your help
